title: Weird Sea Animals
destination: docs
baseurl: ""
# baseurl: "/CSS-Advanced-Project"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
